//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Awareness.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Awareness.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Active Hours.
        /// </summary>
        public static string ActiveHours {
            get {
                return ResourceManager.GetString("ActiveHours", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Awareness reminder is already running in the system tray..
        /// </summary>
        public static string AlreadyRunning {
            get {
                return ResourceManager.GetString("AlreadyRunning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Awareness reminder.
        /// </summary>
        public static string Awareness {
            get {
                return ResourceManager.GetString("Awareness", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Awareness reminder Settings.
        /// </summary>
        public static string AwarenessSettings {
            get {
                return ResourceManager.GetString("AwarenessSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Behavior.
        /// </summary>
        public static string Behavior {
            get {
                return ResourceManager.GetString("Behavior", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Blackout Duration.
        /// </summary>
        public static string BlackoutDuration {
            get {
                return ResourceManager.GetString("BlackoutDuration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Blackout Visual.
        /// </summary>
        public static string BlackoutVisual {
            get {
                return ResourceManager.GetString("BlackoutVisual", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Breathe..
        /// </summary>
        public static string Breathe {
            get {
                return ResourceManager.GetString("Breathe", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Choose....
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Custom Text.
        /// </summary>
        public static string CustomText {
            get {
                return ResourceManager.GetString("CustomText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Display text:.
        /// </summary>
        public static string DisplayText {
            get {
                return ResourceManager.GetString("DisplayText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to End gong (end of blackout).
        /// </summary>
        public static string EndGong {
            get {
                return ResourceManager.GetString("EndGong", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to When on, ESC cannot dismiss the blackout early..
        /// </summary>
        public static string HandcuffsDescription {
            get {
                return ResourceManager.GetString("HandcuffsDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Handcuffs mode.
        /// </summary>
        public static string HandcuffsMode {
            get {
                return ResourceManager.GetString("HandcuffsMode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} hour.
        /// </summary>
        public static string HourFormat {
            get {
                return ResourceManager.GetString("HourFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} hours.
        /// </summary>
        public static string HoursFormat {
            get {
                return ResourceManager.GetString("HoursFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to How to Use Awareness reminder.
        /// </summary>
        public static string HowToUseMenu {
            get {
                return ResourceManager.GetString("HowToUseMenu", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Awareness reminder runs quietly in your system tray (☯ icon).
        ///
        ///How it works:
        ///...
        /// </summary>
        public static string HowToUseText {
            get {
                return ResourceManager.GetString("HowToUseText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to How to Use Awareness reminder.
        /// </summary>
        public static string HowToUseTitle {
            get {
                return ResourceManager.GetString("HowToUseTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Image:.
        /// </summary>
        public static string ImageLabel {
            get {
                return ResourceManager.GetString("ImageLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Interval Between Blackouts.
        /// </summary>
        public static string IntervalBetweenBlackouts {
            get {
                return ResourceManager.GetString("IntervalBetweenBlackouts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Launch at Login.
        /// </summary>
        public static string LaunchAtLogin {
            get {
                return ResourceManager.GetString("LaunchAtLogin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} minutes.
        /// </summary>
        public static string MinutesFormat {
            get {
                return ResourceManager.GetString("MinutesFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Next blackout in {0}.
        /// </summary>
        public static string NextBlackoutIn {
            get {
                return ResourceManager.GetString("NextBlackoutIn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Awareness reminder — Next in {0}.
        /// </summary>
        public static string NextIn {
            get {
                return ResourceManager.GetString("NextIn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string NoneLabel {
            get {
                return ResourceManager.GetString("NoneLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No video selected.
        /// </summary>
        public static string NoVideoSelected {
            get {
                return ResourceManager.GetString("NoVideoSelected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to now.
        /// </summary>
        public static string Now {
            get {
                return ResourceManager.GetString("Now", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Plain Black.
        /// </summary>
        public static string PlainBlack {
            get {
                return ResourceManager.GetString("PlainBlack", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quit Awareness reminder.
        /// </summary>
        public static string QuitAwareness {
            get {
                return ResourceManager.GetString("QuitAwareness", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scheduling....
        /// </summary>
        public static string Scheduling {
            get {
                return ResourceManager.GetString("Scheduling", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings....
        /// </summary>
        public static string SettingsMenu {
            get {
                return ResourceManager.GetString("SettingsMenu", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Snooze.
        /// </summary>
        public static string Snooze {
            get {
                return ResourceManager.GetString("Snooze", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Snoozed indefinitely.
        /// </summary>
        public static string SnoozedIndefinitely {
            get {
                return ResourceManager.GetString("SnoozedIndefinitely", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Snoozed until {0}.
        /// </summary>
        public static string SnoozedUntil {
            get {
                return ResourceManager.GetString("SnoozedUntil", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        public static string Sound {
            get {
                return ResourceManager.GetString("Sound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start gong (begin of blackout).
        /// </summary>
        public static string StartGong {
            get {
                return ResourceManager.GetString("StartGong", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Test Blackout.
        /// </summary>
        public static string TestBlackout {
            get {
                return ResourceManager.GetString("TestBlackout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Awareness reminder — Snoozed indefinitely.
        /// </summary>
        public static string TooltipSnoozedIndefinitely {
            get {
                return ResourceManager.GetString("TooltipSnoozedIndefinitely", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Awareness reminder — Snoozed until {0}.
        /// </summary>
        public static string TooltipSnoozedUntil {
            get {
                return ResourceManager.GetString("TooltipSnoozedUntil", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Until.
        /// </summary>
        public static string Until {
            get {
                return ResourceManager.GetString("Until", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Until I resume.
        /// </summary>
        public static string UntilIResume {
            get {
                return ResourceManager.GetString("UntilIResume", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Update Available (v{0}).
        /// </summary>
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Video:.
        /// </summary>
        public static string VideoLabel {
            get {
                return ResourceManager.GetString("VideoLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Welcome to Awareness reminder.
        /// </summary>
        public static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Awareness reminder is now running in your system tray.
        ///
        ///Look for the ☯ icon in the bottom-right of your screen....
        /// </summary>
        public static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lifetime.
        /// </summary>
        public static string Lifetime {
            get {
                return ResourceManager.GetString("Lifetime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Progress....
        /// </summary>
        public static string ProgressMenu {
            get {
                return ResourceManager.GetString("ProgressMenu", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string ProgressTitle {
            get {
                return ResourceManager.GetString("ProgressTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Success Rate.
        /// </summary>
        public static string SuccessRate {
            get {
                return ResourceManager.GetString("SuccessRate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to triggered.
        /// </summary>
        public static string Triggered {
            get {
                return ResourceManager.GetString("Triggered", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to About Awareness reminder....
        /// </summary>
        public static string AboutMenu {
            get {
                return ResourceManager.GetString("AboutMenu", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A mindfulness timer for your PC.
        ///Randomly pauses your screen to help you breathe.
        ///...
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Awareness reminder.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
    }
}
