import Foundation
import CryptoKit

/// Manages the sync passphrase on macOS. The user enters the 4-word + number key
/// generated by the iOS app. The passphrase is hashed with SHA-256 before being
/// sent to Supabase.
final class SyncKeyManager {

    static let shared = SyncKeyManager()

    private let defaults = UserDefaults.standard

    private enum Keys {
        static let syncPassphrase = "syncPassphrase"
    }

    /// The sync passphrase entered by the user (e.g. "lotus-ember-cedar-moonrise-42")
    var passphrase: String? {
        get { defaults.string(forKey: Keys.syncPassphrase) }
        set { defaults.set(newValue, forKey: Keys.syncPassphrase) }
    }

    /// Whether a sync passphrase has been entered
    var isConfigured: Bool {
        guard let phrase = passphrase else { return false }
        return !phrase.trimmingCharacters(in: .whitespaces).isEmpty
    }

    /// SHA-256 hex digest of the passphrase, used as the sync_key in Supabase
    var hashedSyncKey: String? {
        guard let phrase = passphrase, !phrase.isEmpty else { return nil }
        // Normalize: lowercase, trim whitespace
        let normalized = phrase.lowercased().trimmingCharacters(in: .whitespaces)
        let data = Data(normalized.utf8)
        let hash = SHA256.hash(data: data)
        return hash.compactMap { String(format: "%02x", $0) }.joined()
    }

    private init() {}
}
