import Foundation
import CryptoKit

/// Manages the sync passphrase on macOS. The user enters the 4-word + number key
/// generated by the iOS app. The passphrase is hashed with SHA-256 before being
/// sent to Supabase.
final class SyncKeyManager {

    static let shared = SyncKeyManager()

    private let defaults = UserDefaults.standard

    private enum Keys {
        static let syncPassphrase = "syncPassphrase"
        static let lastPullDate = "syncLastPullDate"
        static let processedEventIDs = "syncProcessedEventIDs"
    }

    /// The sync passphrase entered by the user (e.g. "lotus-ember-cedar-moonrise-42")
    var passphrase: String? {
        get { defaults.string(forKey: Keys.syncPassphrase) }
        set { defaults.set(newValue, forKey: Keys.syncPassphrase) }
    }

    /// Whether a sync passphrase has been entered
    var isConfigured: Bool {
        guard let phrase = passphrase else { return false }
        return !phrase.trimmingCharacters(in: .whitespaces).isEmpty
    }

    /// SHA-256 hex digest of the passphrase, used as the sync_key in Supabase
    var hashedSyncKey: String? {
        guard let phrase = passphrase, !phrase.isEmpty else { return nil }
        // Normalize: lowercase, trim whitespace
        let normalized = phrase.lowercased().trimmingCharacters(in: .whitespaces)
        let data = Data(normalized.utf8)
        let hash = SHA256.hash(data: data)
        return hash.compactMap { String(format: "%02x", $0) }.joined()
    }

    // MARK: - Pull Sync State

    /// Last time events were pulled from Supabase
    var lastPullDate: Date? {
        get { defaults.object(forKey: Keys.lastPullDate) as? Date }
        set { defaults.set(newValue, forKey: Keys.lastPullDate) }
    }

    /// IDs of events already integrated into ProgressTracker (dedup)
    var processedEventIDs: Set<String> {
        get {
            let array = defaults.array(forKey: Keys.processedEventIDs) as? [String] ?? []
            return Set(array)
        }
        set {
            // Cap at 5000 entries to prevent unbounded growth
            var ids = newValue
            if ids.count > 5000 {
                ids = Set(ids.sorted().suffix(5000))
            }
            defaults.set(Array(ids), forKey: Keys.processedEventIDs)
        }
    }

    private init() {}
}
