using System.Security.Cryptography;
using System.Text;

namespace Awareness.Sync;

/// <summary>
/// Manages the sync passphrase on Windows. The user enters the 4-word + number key
/// generated by the iOS app. The passphrase is hashed with SHA-256 before being
/// sent to Supabase.
/// </summary>
public class SyncKeyManager
{
    public static SyncKeyManager Shared { get; } = new();

    /// <summary>The sync passphrase entered by the user (e.g. "lotus-ember-cedar-moonrise-42")</summary>
    public string Passphrase
    {
        get => Settings.SettingsManager.Shared.SyncPassphrase;
        set => Settings.SettingsManager.Shared.SyncPassphrase = value;
    }

    /// <summary>Whether a sync passphrase has been entered</summary>
    public bool IsConfigured
    {
        get
        {
            var phrase = Passphrase;
            return !string.IsNullOrWhiteSpace(phrase);
        }
    }

    /// <summary>SHA-256 hex digest of the passphrase, used as the sync_key in Supabase</summary>
    public string? HashedSyncKey
    {
        get
        {
            var phrase = Passphrase;
            if (string.IsNullOrWhiteSpace(phrase)) return null;

            var normalized = phrase.ToLowerInvariant().Trim();
            var bytes = Encoding.UTF8.GetBytes(normalized);
            var hash = SHA256.HashData(bytes);
            return BitConverter.ToString(hash).Replace("-", "").ToLowerInvariant();
        }
    }

    private SyncKeyManager() { }
}
